### PR TITLE
Do not setgroups() on FreeBSD

### PR DESCRIPTION
**Pull request by kiryanov**
setgroups() call will fail with EPERM on FreeBSD. It renders --user and --uid options useless.

### CODE REVIEW

**Comment by bol-van** [comment]
It doesn't reproduce on my system
What is your BSD version ?

**Comment by kiryanov** [comment]
14.1. I run it from root as a daemon, it drops privileges with no issues, but a call to setgroups fails.
PS: setgroups invocation differs between linux and freebsd, in particular freebsd needs a primary group to be specified twice in the list of groups, maybe that’s the issue. I can do some more testing in a week or two.

**Comment by bol-van** [comment]
the only call to setgroups is
`setgroups(0,NULL);`
it's intended to drop all supplimentary groups

**Comment by kiryanov** [comment]
So I have conducted quite some testing and I definitely could not make it work with setgroups() on FreeBSD 14.1 even using the FreeBSD semantics and passing the primary gid as the first member of the groups array.
Maybe instead of removing the call just make the error non-fatal? Most of the code I have looked at just prints a warning if setgroups() call fails.

**Comment by bol-van** [comment]
may be you share your test code ?
i cant reproduce what you talk about

**Pull request closed without merging**
