### PR TITLE
Added docs for OPNsense

### PR DESCRIPTION
**Pull request by bubundas17**
I tried following the docs to set it up on OPNsense router. and after some fiddling around, it did work. 

**Tested With:**
OPNsense 23.1.7_3-amd64
FreeBSD 13.1-RELEASE-p7
OpenSSL 1.1.1t 7 Feb 2023

### CODE REVIEW

**Comment by LowderPlay** [comment]
This worked for me, but I had to use the original startup script, mentioned in the pfSense section.

**Comment by tribalRu** [comment]
> This worked for me, but I had to use the original startup script, mentioned in the pfSense section.

Hi. Can you tell me how you got it to work? For some reason it doesn't work as described. Actually it doesn't work at all, if I run dvtws in the console there are a lot of errors: 
`reinject sendto: Permission denied`
and thats all

**Comment by bol-van** [comment]
may be you set up some restricitve fw rules that prevent processes from sending packets ?

**Comment by tribalRu** [comment]
Ну, по идее все что внутри сети не запрещено, запрещающие только для входящих стоят. И в файрволе с этого устройства нет ни одного вхождения по заблокированным запросам

**Comment by LowderPlay** [comment]
I also encountered `reinject sendto: Permission denied` errors. 
Make sure, that you run `pfctl -d ; pfctl -e` after starting `dvtws`, as specified in the pfSense guide.

**Comment by tribalRu** [comment]
Thanks. It seems to be working now. We'll have to test it more. Strange that it didn't work earlier.

**Comment by bubundas17** [comment]
Nice to see that there is finally some activity in this pull request. :)

**Comment by tribalRu** [comment]
Yes, just need to correct the text, the information is not complete. I'll test it for a few days and create a PR for the author to update and add it to the official documentation).

**Comment by bol-van** [comment]
may be i'll manage to work it with pf divert-to
have some ideas
if so there will be another option

**Comment by tribalRu** [comment]
that would be great!

**Pull request closed without merging**
