### PR TITLE
Add runit & s6 service

### PR DESCRIPTION
**Pull request by lepz0r**
Currently no `install_easy.sh` support

### CODE REVIEW

**Comment by bol-van** [comment]
what is the purpose of : exec chpst -b zapret pause
?

runit does not support forking ?
it considers services is running until startup script exits ?
what mechanism it uses to manually stop a service ?

**Comment by lepz0r** [comment]
`exec chpst -b zapret pause` is to keep zapret service running, in runit we use `finish` script to run a script to stop the service

**Comment by bol-van** [comment]
I see you correctly call in your finish script sysv stop  from zapret
This will unconfigure ip/nf tables and stop daemon(s)
But what about running "pause" ?
What makes it to exit  ?
What if pause does not run at all ?

**Comment by lepz0r** [comment]
without pause line it will stop the service as soon as the init script finished

**Comment by bol-van** [comment]
I tried to install runit in debian.
Service keeps starting and stopping every few seconds.

chpst: fatal: unable to run: zapret: file does not exist

pause command does not exist

**Comment by lepz0r** [comment]
try to run it on Artix or Void

**Comment by bol-van** [comment]
```
bash-5.1# xbps-query -s runit-void
[*] runit-void-20220329_1 Void Linux runit scripts
bash-5.1# xbps-query -f runit-void | grep pause
/usr/bin/pause
/usr/share/man/man1/pause.1

```

from what I read and understand    runit startup system requires daemons not to fork.   my sysv init script DO fork and that's why pause is required to prevent the service from stopping immediately

however, in void linux /usr/bin/pause command belong to package 'runit-void'. it looks like specific to void linux, isn't it ?
what is generic replacement for the pause command ?

**Comment by lepz0r** [comment]
try to change `exec chpst -b zapret pause` to `exec chpst -b zapret sleep infinity`

**Comment by bol-van** [comment]
Yes, I also came to 'sleep' but wanted to call it with 0xFFFFFFFF seconds.
Looks like debian 'sleep inf' command calls 'pause' syscall  insted on 'nanosleep'
Busybox calls nanosleep with 0x7FFFFFFF seconds

**Comment by bol-van** [comment]
Last question : i dont know where s6 is used.  Is it OK to have all those scripts without +x chmod ?

**Comment by lepz0r** [comment]
It's service files for s6 init & yes it's OK to have them without +x chmod

**Comment by bol-van** [comment]
I installed s6 to debian.  Still dont understand how to use it.
According to docs it wants run, not up and down.
What am I doing wrong ?
```
s6-svscan /opt/zapret/init.d/s6
s6-supervise zapret (child): fatal: unable to exec run: No such file or directory
s6-supervise zapret: warning: unable to spawn ./run - waiting 10 seconds
```

**Comment by bol-van** [comment]
OK,  Its not for s6 but for s6-rc
s6 is for longruns only,   oneshots are not served by s6 supervisor

**Pull request merged**
